---
- name: Install iTerm2
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Check if iTerm2 is installed
      ansible.builtin.stat:
        path: /Applications/iTerm.app
      register: iterm2_installed

    - name: Install iTerm2
      ansible.builtin.command: >
        open "https://iterm2.com/downloads/stable/iTerm2-3.4.9.zip"
      when: not iterm2_installed.stat.exists

    - name: Inform user
      ansible.builtin.debug:
        msg: "iTerm2 is already installed."
      when: iterm2_installed.stat.exists
